mod about;
pub mod admin;
mod article_detail;
mod articles;
mod contact;
mod home;
mod portfolio;
mod portfolio_detail;
mod service_detail;
mod services;

pub use about::About;
pub use admin::*;
pub use article_detail::ArticleDetail;
pub use articles::Articles;
pub use contact::Contact;
pub use home::Home;
pub use portfolio::Portfolio;
pub use portfolio_detail::PortfolioDetail;
pub use service_detail::ServiceDetail;
pub use services::Services;
